# Server information
host: localhost
port: 5432

# Orpheus Home dir
# orpheus_home: /var/lib/postgresql/11/main/base/13125 #Please specify the Orpheus home directory
orpheus_home: /home/ailyn/Documents/git/implementation

orpheus_data: /data

# Meta dir 
# TODO: hide them under orpheus_home
log_path: .meta/logs/log.out
user_log: .meta/user_log
commit_path: .meta/commit_tables
meta_info: .meta/tracker
meta_modifiedIds: .meta/modified
vGraph_json: .meta/vGraph_json

